version: '3.3'

services:
    api:
        build: ./api
        volumes:
        - ./api:/api
        container_name: flask
        ports:
        - "5000:5000"
        - "5678:5678"   
    db:
        image: mysql:8.0
        container_name: mysql
        volumes: 
            - db-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel

    app:
        build: ./app
        container_name: laravel
        entrypoint: '/usr/local/bin/docker-php-entrypoint-dev'
        command: ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"]
        volumes:
            - ./app/src:/var/www/app
        environment: 
            - APP_ENV=local
            - APP_KEY=base64:tLmYfUrrZITzLIkSjFnV+PCAFxkdU+duUxjVSIlrrHo=
            - APP_DEBUG=true
            - DB_CONNECTION=mysql
            - DB_HOST=db ## same as the database service name
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
        restart: unless-stopped
        ports: 
            - 8000:80
        depends_on:
            - db
volumes:
    db-data: